language: objective-c # even when you use Swift, this should still be objective-c
osx_image: xcode10.2

branches:
  only:
  - master

  before_install:
  - gem install bundler

  install:
  - gem update --system
  - bundle install
  - bundle exec fastlane add_plugin telegram

script:
  - echo -e "machine github.com\n  login Kylmakalle\n  password $CI_USER_PASSWORD" > ~/.netrc
  - cd .. && git clone https://Kylmakalle:$CI_USER_PASSWORD@github.com/Kylmakalle/Telegram-iOS-Shared.git
  - cd Telegram-iOS-Private
  - ls -l
  # If not pull request, deploy a new TestFlight build
  - if [ "$TRAVIS_PULL_REQUEST" == false ]; then
       git pull;
       brew install pkg-config yasm;
       bundle exec fastlane build_ci;
    fi;