language: objective-c # even when you use Swift, this should still be objective-c
osx_image: xcode10.2 # or another Xcode version you use

branches:
  only:
  - master

  before_install:
  - echo -e "machine github.com\n  login Kylmakalle\n  password $CI_USER_PASSWORD" > ~/.netrc
  - gem install bundler

  install:
  - gem update --system
  - brew install pkg-config yasm
  - bundle install
  - bundle exec fastlane add_plugin telegram

script:
  # # Exit immediately if one of the commands fails
  # - set -e
  - cd .. && git clone https://Kylmakalle:$CI_USER_PASSWORD@github.com/Kylmakalle/Telegram-iOS-Shared.git
  - cd Telegram-iOS
  - ls -l
  # If not pull request, deploy a new TestFlight build
  - if [ "$TRAVIS_PULL_REQUEST" == false ]; then
       bundle exec fastlane environment && bundle exec fastlane build_ci;
    fi;